services:
  api:
    container_name: customer-management
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - "5000:8080"
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - ConnectionStrings__DefaultConnection=Server=database;Database=CustomerManagement;User Id=cl;Password=123AbC@$;
    networks:
      - backend
    depends_on:
      - database
  database:
    image: mcr.microsoft.com/mssql/server
    container_name: customer-db
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=123AbC@$
      - ACCEPT_EULA=Y
    networks:
      - backend
    volumes:
      - customer_data:/var/opt/mssql
networks:
  backend:
    driver: bridge
volumes:
  customer_data:
  customer_management_src: